//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ghhh.
    /// </summary>
    //  *** Start programmer edit section *** (ghhh CustomAttributes)

    //  *** End programmer edit section *** (ghhh CustomAttributes)
    [AutoAltered()]
    [Caption("Ghhh")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ghhhE", new string[0])]
    [View("ghhhL", new string[0])]
    public class ghhh : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (ghhh CustomMembers)

        //  *** End programmer edit section *** (ghhh CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ghhhE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ghhhE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ghhhE", typeof(IIS.Test5.ghhh));
                }
            }
            
            /// <summary>
            /// "ghhhL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ghhhL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ghhhL", typeof(IIS.Test5.ghhh));
                }
            }
        }
    }
}
